### ISSUE TITLE
Problem when running with Swift mode detection script.

### ISSUE THREAD

**Issue by antran22** [kato-k/vim-auto-color-switcher#4]
The Swift mode detection script yield lettercase output: `Light, Dark`

The Vim script here is checking the lowercase strings:
https://github.com/kat0h/vim-auto-color-switcher/blob/1208a8d95a7adc13e68ebb4b78b98c75b68bfaea/plugin/auto_color_switcher.vim#L39

We should either lowercase the output of the Swift script or fix the Vim script.
Anyway, very nifty plugin. Cheers.

**Comment by kat0h** [comment]
thank you for your issue
Vim's comparison operators ignore the case of strings.
But the current code looks strange
Fixed
